language: node_js
node_js:
  - "0.11"
install:
  - "npm install -g typescript"
  - "npm install -g bower"
  - "npm install -g testem"
  - "npm install -g grunt-cli"
before_script:
  - "npm install"
  - "bower install"
  - "grunt test"
script:
  - "testem ci"
branches:
  only:
    - develop
    - master
