language: node_js
node_js:
  - "0.11"
install:
  - "npm install -g typescript"
  - "npm install -g bower"
  - "npm install -g testem"
  - "npm install -g grunt-cli"
before_script:
  - sh .travis/scripts/install_chrome.sh
  - npm install
  - bower install
  - grunt test
script:
  - testem launchers
  - testem ci
branches:
  only:
    - develop
    - master
